#include <string>
#include <vector>

/*
Automatically generated rules. Use 'rulesets.hpp.py' to modify/regenerate.
*/

struct Ruleset {
	private:
		const std::string urlPattern;
		const bool completeProvider;
		const std::vector<std::string> rules;
		const std::vector<std::string> rawRules;
		const std::vector<std::string> referralMarketing;
		const std::vector<std::string> exceptions;
		const std::vector<std::string> redirections;
	
	public:
		Ruleset(
			const std::string urlPattern,
			const bool completeProvider,
			const std::vector<std::string> rules,
			const std::vector<std::string> rawRules,
			const std::vector<std::string> referralMarketing,
			const std::vector<std::string> exceptions,
			const std::vector<std::string> redirections
		) :
			urlPattern(urlPattern),
			completeProvider(completeProvider),
			rules(rules),
			rawRules(rawRules),
			referralMarketing(referralMarketing),
			exceptions(exceptions),
			redirections(redirections)
		{}
		
		const std::string get_url_pattern() const {
			return this -> urlPattern;
		}
		
		const bool get_complete_provider() const {
			return this -> completeProvider;
		}
		
		const std::vector<std::string> get_rules() const {
			return this -> rules;
		}
		
		const std::vector<std::string> get_raw_rules() const {
			return this -> rawRules;
		}
		
		const std::vector<std::string> get_referral_marketing() const {
			return this -> referralMarketing;
		}
		
		const std::vector<std::string> get_exceptions() const {
			return this -> exceptions;
		}
		
		const std::vector<std::string> get_redirections() const {
			return this -> redirections;
		}
};

static const std::vector<Ruleset> rulesets = {
	Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?amazon(?:\\.[a-z]{2,}){1,}",
        false,
        {
            "p[fd]_rd_[a-z]*",
            "qid",
            "srs?",
            "__mk_[a-z]{1,3}_[a-z]{1,3}",
            "spIA",
            "ms3_c",
            "[a-z%0-9]*ie",
            "refRID",
            "colii?d",
            "[^a-z%0-9]adId",
            "qualifier",
            "_encoding",
            "smid",
            "field-lbr_brands_browse-bin",
            "ref_?",
            "th",
            "sprefix",
            "crid",
            "keywords",
            "cv_ct_[a-z]+",
            "linkCode",
            "creativeASIN",
            "ascsubtag",
            "aaxitk",
            "hsa_cr_id",
            "sb-ci-[a-z]+",
            "rnid",
            "dchild",
            "camp",
            "creative",
            "s"
        },
        {
            "\\/ref=[^/?]*"
        },
        {
            "tag",
            "ascsubtag"
        },
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?amazon(?:\\.[a-z]{2,}){1,}\\/gp\\/.*?(?:redirector.html|cart\\/ajax-update.html|video\\/api\\/)",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?amazon(?:\\.[a-z]{2,}){1,}\\/(?:hz\\/reviews-render\\/ajax\\/|message-us\\?|s\\?)"
        },
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?amazon(?:\\.[a-z]{2,}){1,}\\/s\\?",
        false,
        {
            "p[fd]_rd_[a-z]*",
            "qid",
            "srs?",
            "__mk_[a-z]{1,3}_[a-z]{1,3}",
            "spIA",
            "ms3_c",
            "[a-z%0-9]*ie",
            "refRID",
            "colii?d",
            "[^a-z%0-9]adId",
            "qualifier",
            "_encoding",
            "smid",
            "field-lbr_brands_browse-bin",
            "ref_?",
            "th",
            "sprefix",
            "crid",
            "cv_ct_[a-z]+",
            "linkCode",
            "creativeASIN",
            "ascsubtag",
            "aaxitk",
            "hsa_cr_id",
            "sb-ci-[a-z]+",
            "rnid",
            "dchild",
            "camp",
            "creative"
        },
        {
            "\\/ref=[^/?]*"
        },
        {
            "tag"
        },
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?fls-na\\.amazon(?:\\.[a-z]{2,}){1,}",
        true,
        {},
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?google(?:\\.[a-z]{2,}){1,}",
        false,
        {
            "ved",
            "bi[a-z]*",
            "gfe_[a-z]*",
            "ei",
            "source",
            "gs_[a-z]*",
            "site",
            "oq",
            "esrc",
            "uact",
            "cd",
            "cad",
            "gws_[a-z]*",
            "atyp",
            "vet",
            "zx",
            "_u",
            "je",
            "dcr",
            "ie",
            "sei",
            "sa",
            "dpr",
            "btn[a-z]*",
            "usg",
            "cd",
            "cad",
            "uact",
            "aqs",
            "sourceid",
            "sxsrf",
            "rlz",
            "i-would-rather-use-firefox",
            "pcampaignid"
        },
        {},
        {
            "referrer"
        },
        {
            "^https?:\\/\\/mail\\.google\\.com\\/mail\\/u\\/",
            "^https?:\\/\\/(?:docs|accounts)\\.google(?:\\.[a-z]{2,}){1,}",
            "^https?:\\/\\/([a-z0-9-\\.])*drive\\.google\\.com\\/videoplayback",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?google(?:\\.[a-z]{2,}){1,}(?:\\/upload)?\\/drive\\/",
            "^https?:\\/\\/news\\.google\\.com.*\\?hl=.",
            "^https?:\\/\\/hangouts\\.google\\.com\\/webchat.*?zx=.",
            "^https?:\\/\\/client-channel\\.google\\.com\\/client-channel.*?zx=.",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?google(?:\\.[a-z]{2,}){1,}\\/s\\?tbm=map.*?gs_[a-z]*=.",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?google(?:\\.[a-z]{2,}){1,}\\/(?:complete\\/search|setprefs|searchbyimage)",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?google(?:\\.[a-z]{2,}){1,}\\/(?:appsactivity|aclk\\?)"
        },
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?google(?:\\.[a-z]{2,}){1,}\\/url\\?.*?(?:url|q)=(https?[^&]+)",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?google(?:\\.[a-z]{2,}){1,}\\/.*?adurl=([^&]+)",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?google(?:\\.[a-z]{2,}){1,}\\/amp\\/s\\/([^&]+)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?google(?:\\.[a-z]{2,}){1,}\\/search\\?",
        false,
        {
            "client",
            "sclient"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?googlesyndication\\.com",
        true,
        {},
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?doubleclick(?:\\.[a-z]{2,}){1,}",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?doubleclick(?:\\.[a-z]{2,}){1,}\\/.*?tag_for_child_directed_treatment=;%3F([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?googleadservices\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?googleadservices\\.com\\/.*?adurl=([^&]*)"
        }
    ),
    Ruleset(
        ".*",
        false,
        {
            "(?:%3F)?utm(?:_[a-z_]*)?",
            "(?:%3F)?ga_[a-z_]+",
            "(?:%3F)?yclid",
            "(?:%3F)?_openstat",
            "(?:%3F)?fb_action_(?:types|ids)",
            "(?:%3F)?fb_(?:source|ref)",
            "(?:%3F)?fbclid",
            "(?:%3F)?action_(?:object|type|ref)_map",
            "(?:%3F)?gs_l",
            "(?:%3F)?mkt_tok",
            "(?:%3F)?hmb_(?:campaign|medium|source)",
            "(?:%3F)?ref_?",
            "(?:%3F)?referrer",
            "(?:%3F)?gclid",
            "(?:%3F)?otm_[a-z_]*",
            "(?:%3F)?cmpid",
            "(?:%3F)?os_ehash",
            "(?:%3F)?_ga",
            "(?:%3F)?_gl",
            "(?:%3F)?__twitter_impression",
            "(?:%3F)?wt_?z?mc",
            "(?:%3F)?wtrid",
            "(?:%3F)?[a-z]?mc",
            "(?:%3F)?dclid",
            "Echobox",
            "(?:%3F)?spm",
            "(?:%3F)?vn(?:_[a-z]*)+",
            "(?:%3F)?tracking_source",
            "(?:%3F)?ceneo_spo"
        },
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?matrix\\.org\\/_matrix\\/",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?(?:cloudflare\\.com|prismic\\.io|tangerine\\.ca|gitlab\\.com)",
            "^https?:\\/\\/myaccount.google(?:\\.[a-z]{2,}){1,}",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?gcsip\\.(?:com|nl)[^?]*\\?.*?&?ref_?=.",
            "^https?:\\/\\/[^/]+/[^/]+/[^/]+\\/-\\/refs\\/switch[^?]*\\?.*?&?ref_?=.",
            "^https?:\\/\\/bugtracker\\.[^/]*\\/[^?]+\\?.*?&?ref_?=[^/?&]*",
            "^https?:\\/\\/comment-cdn\\.9gag\\.com\\/.*?comment-list.json\\?",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?battle\\.net\\/login",
            "^https?:\\/\\/blizzard\\.com\\/oauth2",
            "^https?:\\/\\/kreditkarten-banking\\.lbb\\.de",
            "^https?:\\/\\/www\\.tinkoff\\.ru",
            "^https?:\\/\\/www\\.cyberport\\.de\\/adscript\\.php",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?tweakers\\.net\\/ext\\/lt\\.dsp\\?.*?(?:%3F)?&?ref_?=.",
            "^https?:\\/\\/git(lab)?\\.[^/]*\\/[^?]+\\?.*?&?ref_?=[^/?&]*",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?amazon(?:\\.[a-z]{2,}){1,}\\/message-us\\?",
            "^https?:\\/\\/authorization\\.td\\.com",
            "^https?:\\/\\/support\\.steampowered\\.com",
            "^https?:\\/\\/privacy\\.vakmedianet\\.nl\\/.*?ref=",
            "^https?:\\/\\/sso\\.serverplan\\.com\\/manage2fa\\/check\\?ref=",
            "^https?:\\/\\/login\\.meijer\\.com\\/.*?\\?ref=",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?facebook\\.com\\/(?:login_alerts|ajax|should_add_browser)/",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?facebook\\.com\\/groups\\/member_bio\\/bio_dialog\\/",
            "^https?:\\/\\/api\\.taiga\\.io",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?gog\\.com\\/click\\.html",
            "^https?:\\/\\/login\\.progressive\\.com",
            "^https?:\\/\\/www\\.sephora\\.com\\/api\\/",
            "^https?:\\/\\/www\\.contestgirl\\.com",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?agenciatributaria\\.gob\\.es",
            "^https?:\\/\\/login\\.ingbank\\.pl",
            "^wss?:\\/\\/(?:[a-z0-9-]+\\.)*?zoom\\.us",
            "^https?:\\/\\/api\\.bilibili\\.com",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?onet\\.pl\\/[^?]*\\?.*?utm_campaign=.",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?stripe\\.com\\/[^?]+.*?&?referrer=[^/?&]*",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?lichess\\.org\\/login.*?&?referrer=.*?",
            "^https?:\\/\\/like.co\\/api\\/like\\/likebutton\\/[^?]+.*?&?referrer=[^/?&]*",
            "^https?:\\/\\/button.like.co\\/in\\/.*?&?referrer=[^/?&]*",
            "^https?:\\/\\/www\\.mma\\.go\\.kr",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?github\\.com",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?billiger\\.de\\/.*?mc="
        },
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?adtech(?:\\.[a-z]{2,}){1,}",
        true,
        {},
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?contentpass\\.(?:net|de)",
        true,
        {},
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?bf-ad(?:\\.[a-z]{2,}){1,}",
        true,
        {},
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?amazon-adsystem(?:\\.[a-z]{2,}){1,}",
        true,
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?amazon-adsystem(?:\\.[a-z]{2,}){1,}\\/v3\\/oor\\?"
        },
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?amazon-adsystem(?:\\.[a-z]{2,}){1,}\\/x\\/c\\/.+?\\/([^&]+)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?adsensecustomsearchads(?:\\.[a-z]{2,}){1,}",
        true,
        {},
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?youtube\\.com",
        false,
        {
            "feature",
            "gclid",
            "kw"
        },
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?youtube\\.com\\/signin\\?.*?"
        },
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?youtube\\.com\\/redirect?.*?q=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?youtube\\.com\\/pagead",
        true,
        {},
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?youtube\\.com\\/api\\/stats\\/ads",
        true,
        {},
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?facebook\\.com",
        false,
        {
            "hc_[a-z_%\\[\\]0-9]*",
            "[a-z]*ref[a-z]*",
            "__tn__",
            "eid",
            "__(?:xts|cft)__(?:\\[|%5B)\\d(?:\\]|%5D)",
            "comment_tracking",
            "dti",
            "app",
            "video_source",
            "ftentidentifier",
            "pageid",
            "padding",
            "ls_ref",
            "action_history",
            "tracking",
            "referral_code",
            "referral_story_type"
        },
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?facebook\\.com\\/.*?(plugins|ajax)\\/",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?facebook\\.com\\/dialog\\/(?:share|send)",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?facebook\\.com\\/groups\\/member_bio\\/bio_dialog\\/",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?facebook\\.com\\/photo\\.php\\?",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?facebook\\.com\\/privacy\\/specific_audience_selector_dialog\\/",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?facebook\\.com\\/photo\\/download\\/"
        },
        {
            "^https?:\\/\\/l[a-z]?\\.facebook\\.com/l\\.php\\?.*?u=(https?%3A%2F%2F[^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?twitter.com",
        false,
        {
            "(?:ref_?)?src",
            "s",
            "cn",
            "ref_url"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?reddit.com",
        false,
        {
            "%24deep_link",
            "\\$deep_link",
            "correlation_id",
            "ref_campaign",
            "ref_source",
            "%243p",
            "\\$3p",
            "%24original_url",
            "\\$original_url",
            "_branch_match_id"
        },
        {},
        {},
        {},
        {
            "^https?:\\/\\/out\\.reddit\\.com\\/.*?url=([^&]*)",
            "^https?:\\/\\/click\\.redditmail\\.com\\/.*?url=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?netflix.com",
        false,
        {
            "trackId",
            "tctx",
            "jb[a-z]*?"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?techcrunch\\.com",
        false,
        {
            "ncid",
            "sr",
            "sr_share"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?bing(?:\\.[a-z]{2,}){1,}",
        false,
        {
            "cvid",
            "form",
            "sk",
            "sp",
            "sc",
            "qs",
            "qp"
        },
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?bing(?:\\.[a-z]{2,}){1,}\\/WS\\/redirect\\/"
        },
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?tweakers\\.net",
        false,
        {
            "nb",
            "u"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?twitch\\.com",
        false,
        {
            "tt_medium",
            "tt_content"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?vivaldi\\.com",
        false,
        {
            "pk_campaign",
            "pk_kwd"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?indeed\\.com",
        false,
        {
            "from",
            "alid",
            "[a-z]*tk"
        },
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?indeed\\.com\\/rc\\/clk"
        },
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?hh\\.ru",
        false,
        {
            "vss",
            "t",
            "swnt",
            "grpos",
            "ptl",
            "stl",
            "exp",
            "plim"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?ebay(?:\\.[a-z]{2,}){1,}",
        false,
        {
            "_trkparms",
            "_trksid",
            "_from",
            "hash"
        },
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?rover\\.ebay(?:\\.[a-z]{2,}){1,}\\/rover.*mpre=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?cnet\\.com",
        false,
        {
            "ftag"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?imdb\\.com",
        false,
        {
            "ref_",
            "pf_rd_[a-z]*"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?govdelivery\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?links\\.govdelivery\\.com.*\\/track\\?.*(https?:\\/\\/.*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?walmart\\.com",
        false,
        {
            "u1",
            "ath[a-z]*"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?net\\-parade\\.it",
        false,
        {
            "pl"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?prvnizpravy\\.cz",
        false,
        {
            "xid"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?youku\\.com",
        false,
        {
            "tpa"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?nytimes\\.com",
        false,
        {
            "smid"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?tchibo\\.de",
        false,
        {
            "wbdcd"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?steampowered\\.com",
        false,
        {
            "snr"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?steamcommunity\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?steamcommunity\\.com\\/linkfilter\\/\\?url=([^&]*)"
        }
    ),
    Ruleset(
        "https?:\\/\\/outgoing\\.prod\\.mozaws\\.net\\/",
        false,
        {},
        {},
        {},
        {},
        {
            "https?:\\/\\/[^/]+\\/v1\\/[0-9a-f]{64}\\/(.*)"
        }
    ),
    Ruleset(
        "https?:\\/\\/([a-z0-9-.]*\\.)shutterstock\\.com",
        false,
        {
            "src"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?mozilla\\.org",
        false,
        {
            "src",
            "platform",
            "redirect_source"
        },
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?mozilla.org\\/api"
        },
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?readdc\\.com",
        false,
        {
            "ref"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?dailycodingproblem\\.com",
        false,
        {
            "email"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?github\\.com",
        false,
        {
            "email_token",
            "email_source"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?deviantart\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?deviantart\\.com\\/.*?\\/outgoing\\?(.*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?site2\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?site2\\.com.*?\\?.*=(.*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?site\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?site\\.com.*?\\?to=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?site3\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?site3\\.com.*?\\?r=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?aliexpress(?:\\.[a-z]{2,}){1,}",
        false,
        {
            "ws_ab_test",
            "btsid",
            "algo_expid",
            "algo_pvid",
            "gps-id",
            "scm[_a-z-]*",
            "cv",
            "af",
            "mall_affr",
            "sk",
            "dp",
            "terminal_id",
            "aff_request_id"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?mozillazine\\.org",
        false,
        {
            "sid"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?9gag\\.com",
        false,
        {
            "ref"
        },
        {},
        {},
        {
            "^https?:\\/\\/comment-cdn\\.9gag\\.com\\/.*?comment-list.json\\?"
        },
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?linksynergy\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?linksynergy\\.com\\/.*?murl=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?giphy\\.com",
        false,
        {
            "ref"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?gate\\.sc",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?gate\\.sc\\/.*?url=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/vk\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/vk\\.com\\/away\\.php\\?to=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?woot\\.com",
        false,
        {
            "ref_?"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?vitamix\\.com",
        false,
        {
            "_requestid",
            "cid",
            "dl",
            "di",
            "sd",
            "bi"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?curseforge\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?curseforge\\.com\\/linkout\\?remoteUrl=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?messenger\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/l\\.messenger\\.com\\/l\\.php\\?u=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?nypost\\.com",
        false,
        {
            "__twitter_impression"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?ozon\\.ru",
        false,
        {
            "partner"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?norml\\.org",
        false,
        {
            "link_id",
            "can_id",
            "source",
            "email_referrer",
            "email_subject"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?linkedin\\.com",
        false,
        {
            "refId",
            "trk",
            "li[a-z]{2}"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?linkedin\\.com\\/learning",
        false,
        {
            "u"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?smartredirect\\.de",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?smartredirect\\.de.*?url=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?spiegel\\.de",
        false,
        {
            "b"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?rutracker\\.org",
        false,
        {},
        {},
        {},
        {},
        {
            ".*url=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?instagram\\.com",
        false,
        {
            "igshid"
        },
        {},
        {},
        {},
        {
            ".*u=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?lazada\\.com\\.my",
        false,
        {
            "ad_src",
            "did",
            "pa",
            "mp",
            "impsrc",
            "cid",
            "pos"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?imgsrc\\.ru",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?dlp\\.imgsrc\\.ru\\/go\\/\\d+\\/\\d+\\/\\d+\\/([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?boredpanda\\.com",
        false,
        {
            "h"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?awstrack\\.me",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?awstrack\\.me\\/.*\\/(https?.*?)\\/"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?exactag\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?exactag\\.com.*url=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?bahn\\.de",
        false,
        {
            "dbkanal_[0-9]{3}"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?disq\\.us",
        false,
        {
            "cuid"
        },
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?disq\\.us\\/.*?url=([^&]*)%3A"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?anonym\\.to",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?anonym\\.to.*\\?([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?moosejaw\\.com",
        false,
        {
            "cm_lm",
            "cm_mmc",
            "webUserId",
            "spMailingID",
            "spUserID",
            "spJobID",
            "spReportId"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?spotify\\.com",
        false,
        {
            "si"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?(?:yandex(?:\\.[a-z]{2,}){1,}|ya\\.ru)",
        false,
        {
            "lr",
            "redircnt"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?healio\\.com",
        false,
        {
            "ecp",
            "m_bt"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?zoho\\.com",
        false,
        {
            "iref"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?snapchat\\.com",
        false,
        {
            "sc_referrer",
            "sc_ua"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?medium\\.com",
        false,
        {
            "source"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?swp\\.de",
        false,
        {
            "source"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?wps\\.com",
        false,
        {
            "from"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:accounts\\.)?firefox\\.com",
        false,
        {
            "context",
            "entrypoint",
            "form_type"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:support\\.)?mozilla\\.org",
        false,
        {
            "as"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?diepresse\\.com",
        false,
        {
            "from",
            "xtor",
            "xt_at"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/newsletter\\.lidl(?:\\.[a-z]{2,}){1,}",
        false,
        {
            "x"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?allegro\\.pl",
        false,
        {
            "reco_id",
            "sid"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?backcountry\\.com",
        false,
        {
            "CMP_SKU",
            "MER",
            "mr:trackingCode",
            "mr:device",
            "mr:adType",
            "iv_",
            "CMP_ID",
            "k_clickid",
            "rmatt",
            "INT_ID",
            "ti",
            "fl"
        },
        {},
        {
            "mr:referralID"
        },
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?meetup\\.com",
        false,
        {
            "rv",
            "_xtd"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?apple\\.com",
        false,
        {
            "app",
            "ign-itsc[a-z]+"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?alabout\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?alabout\\.com.*url=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?newyorker\\.com",
        false,
        {
            "source",
            "bxid",
            "cndid",
            "esrc",
            "mbid"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?gog\\.com",
        false,
        {
            "track_click",
            "link_id"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?tradedoubler\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?tradedoubler\\.com.*(?:url|_td_deeplink)=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?theguardian\\.com",
        false,
        {
            "CMP"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?srvtrck\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?srvtrck\\.com.*url=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/mysku\\.ru",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/mysku\\.ru.*r=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?admitad\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?admitad\\.com.*ulp=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?taobao\\.com",
        false,
        {
            "price",
            "sourceType",
            "suid",
            "ut_sk",
            "un",
            "share_crt_v",
            "sp_tk",
            "cpp",
            "shareurl",
            "short_name",
            "app",
            "scm[_a-z-]*",
            "pvid",
            "algo_expid",
            "algo_pvid",
            "ns",
            "abbucket",
            "ali_refid",
            "ali_trackid",
            "acm",
            "utparam",
            "pos",
            "abtest",
            "trackInfo",
            "utkn",
            "scene",
            "mytmenu",
            "turing_bucket",
            "lygClk",
            "impid",
            "bftTag",
            "bftRwd",
            "spm",
            "_u"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?tmall\\.com",
        false,
        {
            "price",
            "sourceType",
            "suid",
            "ut_sk",
            "un",
            "share_crt_v",
            "sp_tk",
            "cpp",
            "shareurl",
            "short_name",
            "app",
            "scm[_a-z-]*",
            "pvid",
            "algo_expid",
            "algo_pvid",
            "ns",
            "abbucket",
            "ali_refid",
            "ali_trackid",
            "acm",
            "utparam",
            "pos",
            "abtest",
            "trackInfo",
            "user_number_id",
            "utkn",
            "scene",
            "mytmenu",
            "turing_bucket",
            "lygClk",
            "impid",
            "bftTag",
            "bftRwd",
            "activity_id"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?tb\\.cn",
        false,
        {
            "sm"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?bilibili\\.com",
        false,
        {
            "callback",
            "spm_id_from",
            "from_source",
            "from",
            "seid",
            "share_source",
            "msource",
            "refer_from",
            "share_medium",
            "share_source",
            "share_plat",
            "share_tag",
            "share_session_id",
            "timestamp",
            "unique_k"
        },
        {},
        {},
        {
            "^https?:\\/\\/api\\.bilibili\\.com"
        },
        {}
    ),
    Ruleset(
        "^https?:\\/\\/m\\.bilibili\\.com",
        false,
        {
            "bbid",
            "ts"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/live\\.bilibili\\.com",
        false,
        {
            "visit_id",
            "session_id",
            "broadcast_type",
            "is_room_feed"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?marketscreener\\.com",
        false,
        {
            "type_recherche",
            "mots",
            "noredirect",
            "RewriteLast",
            "lien",
            "aComposeInputSearch",
            "type_recherche_forum",
            "add_mots",
            "countview"
        },
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?marketscreener\\.com\\/search\\/\\?"
        },
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?marketscreener\\.com\\/search\\/\\?",
        false,
        {
            "type_recherche",
            "noredirect",
            "RewriteLast",
            "lien",
            "aComposeInputSearch",
            "type_recherche_forum",
            "countview"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?bestbuy\\.com",
        false,
        {
            "irclickid",
            "irgwc",
            "loc",
            "acampID",
            "mpid",
            "intl"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?digidip\\.net",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?digidip\\.net.*url=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?tiktok\\.com",
        false,
        {
            "u_code",
            "preview_pb",
            "_d",
            "timestamp",
            "user_id",
            "share_app_name",
            "share_iid",
            "source"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?autoplus\\.fr",
        false,
        {
            "idprob",
            "hash",
            "sending_id",
            "site_id",
            "dr_tracker"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?bigfishgames\\.com",
        false,
        {
            "pc",
            "npc",
            "npv[0-9]+",
            "npi"
        },
        {
            "\\?pc$"
        },
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?dpbolvw\\.net",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?dpbolvw\\.net.*url=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?humblebundle\\.com",
        false,
        {},
        {},
        {
            "partner"
        },
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?cafepedagogique\\.net",
        false,
        {
            "actId",
            "actCampaignType",
            "actSource"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?bloculus\\.com",
        false,
        {
            "tl_[a-z_]+"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?mailpanion\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?mailpanion\\.com.*destination=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?signtr\\.website",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?signtr\\.website.*redirect=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?mailtrack\\.io",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?mailtrack\\.io.*url=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?zillow\\.com",
        false,
        {
            "rtoken"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?realtor\\.com",
        false,
        {
            "ex",
            "identityID",
            "MID",
            "RID"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?redfin\\.com",
        false,
        {
            "riftinfo"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?epicgames\\.com",
        false,
        {
            "epic_affiliate",
            "epic_gameId"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?onet\\.pl",
        false,
        {
            "srcc",
            "utm_v",
            "utm_medium",
            "utm_source"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?allrecipes\\.com",
        false,
        {
            "internalSource",
            "referringId",
            "referringContentType",
            "clickId"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?europe1\\.fr",
        false,
        {
            "xtor"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?effiliation\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?effiliation\\.com.*url=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?argos\\.co\\.uk",
        false,
        {
            "istCompanyId",
            "istFeedId",
            "istItemId",
            "istBid",
            "clickOrigin"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?hlserve\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?hlserve\\.com.*dest=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?thunderbird\\.net",
        false,
        {
            "src"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?cnbc\\.com",
        false,
        {
            "__source"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?roblox\\.com",
        false,
        {
            "refPageId"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?cell\\.com",
        false,
        {
            "_returnURL"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/academic\\.oup\\.com",
        false,
        {
            "redirectedFrom"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?flexlinkspro\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?flexlinkspro\\.com.*url=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?agata88\\.com",
        false,
        {
            "source"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?hs\\.fi",
        false,
        {
            "share"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?yle\\.fi",
        false,
        {
            "origin"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/refer\\.ccbill\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/refer\\.ccbill\\.com.*HTML=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?flipkart\\.com",
        false,
        {
            "otracker.?",
            "ssid",
            "[cilp]id",
            "marketplace",
            "store",
            "srno",
            "store",
            "ppn",
            "ppt",
            "fm",
            "collection-tab-name",
            "sattr\\[\\]",
            "p\\[\\]",
            "st"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?idealo\\.de",
        false,
        {
            "sid",
            "src",
            "siteId",
            "lcb",
            "leadOutUrl",
            "offerListId",
            "osId",
            "cancelUrl",
            "disc"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?idealo-partner\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?idealo-partner\\.com.*trg=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?teletrader\\.com",
        false,
        {
            "internal"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?webgains\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?webgains\\.com.*wgtarget=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?deeplearning\\.ai",
        false,
        {
            "ecid",
            "_hsmi",
            "_hsenc"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?getpocket\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?getpocket\\.com.*url=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?gamespot\\.com",
        false,
        {
            "PostType",
            "ServiceType",
            "ftag",
            "UniqueID",
            "TheTime"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?tokopedia\\.com",
        false,
        {
            "src",
            "trkid",
            "whid"
        },
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?tokopedia\\.com\\/promo.*r=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?wkorea\\.com",
        false,
        {
            "ddw",
            "ds_ch"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?eonline\\.com",
        false,
        {
            "source",
            "medium",
            "content"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?reuters\\.com",
        false,
        {
            "taid"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/app\\.adjust\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/app\\.adjust\\.com.*redirect=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?change\\.org",
        false,
        {
            "source_location",
            "psf_variant",
            "share_intent"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?ceneo\\.pl",
        false,
        {
            "tag"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?wired\\.com",
        false,
        {
            "intcid"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/arms-retcode\\.aliyuncs\\.com",
        false,
        {
            "pid",
            "uid",
            "tag",
            "release",
            "environment",
            "sample",
            "behavior",
            "enableSPA",
            "enableLinkTrace",
            "page",
            "begin",
            "c2",
            "c3",
            "success",
            "code",
            "msg",
            "api",
            "traceId",
            "pv_id",
            "flag",
            "sr",
            "vp",
            "ct",
            "_v",
            "sampling",
            "dl",
            "post_res"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?://(?:[a-z0-9-]+\\.)*?nikkei\\.co(?:m|\\.jp)",
        false,
        {
            "adid",
            "i_cid",
            "n_cid",
            "waad"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?weibo\\.(cn|com)",
        false,
        {
            "weibo_id",
            "dt_dapp"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?fiverr\\.com",
        false,
        {
            "context_referrer",
            "source",
            "ref_ctx_id",
            "funnel"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?etsy\\.com",
        false,
        {
            "click_key",
            "click_sum",
            "organic_search_click"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?magento\\.com",
        false,
        {
            "itm_campaign",
            "itm_medium",
            "itm_source",
            "itm_term"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?novinky\\.cz",
        false,
        {
            "dop_ab_variant",
            "dop_source_zone_name",
            "dop_req_id",
            "dop_id",
            "source",
            "seq_no"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?aktualne\\.cz",
        false,
        {
            "dop_ab_variant",
            "dop_source_zone_name",
            "dop_req_id",
            "dop_id"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?seznamzpravy\\.cz",
        false,
        {
            "dop_ab_variant",
            "dop_source_zone_name",
            "dop_req_id",
            "dop_id",
            "source",
            "seq_no"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?billiger\\.de",
        false,
        {
            "log",
            "p"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?amazon(?:\\.[a-z]{2,})",
        false,
        {
            "hv[a-z]{3,6}",
            "vtargid",
            "h",
            "hydadcr",
            "psc",
            "linkId",
            "language",
            "condition",
            "marketplaceID",
            "s",
            "url",
            "Source",
            "sc_[a-z]+",
            "primeCampaignId",
            "sub",
            "__mk_.+",
            "lmdsid",
            "refinements",
            "rps"
        },
        {
            "\\b\\/.+(?=\\/dp)"
        },
        {
            "tag"
        },
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?amazon(?:\\.[a-z]{2,})\\/gp\\/[a-z]\\.html?.*U=([^&]*)",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?amazon(?:\\.[a-z]{2,})\\/gp\\/redirect\\.html?.*location=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?aliexpress(?:\\.[a-z]{2,})",
        false,
        {
            "srcSns",
            "mb",
            "tid",
            "image",
            "businessType",
            "templateId",
            "title",
            "[A-Za-z]*_?platform",
            "cpt",
            "terminal_id",
            "aff_[a-z_]+",
            "trace",
            "tt",
            "sk",
            "s",
            "spreadType",
            "tmLog",
            "bizType",
            "mergeHashcode",
            "description",
            "templateKey"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?bing\\.com",
        false,
        {
            "pq",
            "toWww",
            "redig",
            "rlid"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?change\\.org",
        false,
        {
            "recruite[a-z_]+",
            "cs_tk",
            "source_location",
            "pt",
            "user_flow"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?facebook\\.com",
        false,
        {
            "h",
            "login_source",
            "_[a-z_]+"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        ".*",
        false,
        {
            "pfm_[a-zA-Z0-9]*",
            "seller[Ii]d",
            "franq",
            "opn",
            "mktportal",
            "gclsrc",
            "_*twitter_impression",
            "partner",
            "cm_mmc",
            "epar",
            "hl",
            "s_term",
            "ref_noscript"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?google(?:\\.[a-z]{2,}){1,}",
        false,
        {
            "client",
            "oe",
            "docid",
            "imgrefurl",
            "amp"
        },
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?google(?:\\.[a-z]{2,}){1,}\\/amp\\/s\\/([^&]*)",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?google(?:\\.[a-z]{2,}){1,}\\/img.+(?:\\?|&)imgurl=([^&]*)",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?google(?:\\.[a-z]{2,}){1,}\\/aclk.+(?:\\?|&)adurl=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?kabum\\.com\\.br",
        false,
        {
            "zanpid",
            "codigo"
        },
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?kabum\\.com\\.br\\/cgi-local\\/site\\/produtos\\/descricao_ofertas\\.cgi\\?.+"
        },
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?mercadoli[bv]re\\.com",
        false,
        {
            "matt_[a-z]+",
            "reco_[a-z]+",
            "\\bc_[a-z]+",
            "no[Ii]ndex",
            "contextual",
            "[a-zA-Z]+ariation",
            "position",
            "type",
            "tracking_id",
            "quantity",
            "reference_id"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?vivo\\.com\\.br",
        false,
        {
            "id_origem_vivo",
            "origin",
            "pid",
            "is_retargeting",
            "shortlink",
            "af_[a-z]+",
            "c(?:_.+)?"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?twitter\\.com",
        false,
        {
            "original_referer",
            "via"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?globo\\.com",
        false,
        {
            "versao"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?americanas\\.com\\.br",
        false,
        {
            "WT\\.srch",
            "acc",
            "o",
            "i"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?(duckduckgo\\.com)",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?duckduckgo.com\\/l\\/\\?.*uddg=([^&]*)",
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?duckduckgo\\.com\\/y\\.js\\?.*u3=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?dell\\.com",
        false,
        {
            "dgseg",
            "cid",
            "ran[a-zA-Z]",
            "gacd",
            "dgc",
            "acd",
            "lid",
            "VEN3"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?onelink\\.me",
        false,
        {
            "af_[a-z]+",
            "pid",
            "c"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?myanimelist\\.net",
        false,
        {
            "_[a-z]+",
            "from",
            "id"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/clickserve\\.dartsearch\\.net",
        true,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/clickserve\\.dartsearch\\.net\\/link\\/click\\?.*ds_dest_url=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/play\\.google\\.com",
        false,
        {
            "pcampaignid"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?elpais\\.com",
        false,
        {
            "ssm",
            "rel",
            "prod",
            "o",
            "prm"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?primevideo\\.com",
        false,
        {},
        {
            "\\/ref=[^/?]*"
        },
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?awscloud\\.com",
        false,
        {
            "sc_[a-z]+",
            "trk"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?natura\\.com\\.br",
        false,
        {
            "iprom_[a-z]+",
            "list_[a-z]+"
        },
        {},
        {
            "consultoria"
        },
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?compracerta\\.com\\.br",
        false,
        {
            "utmi_[a-z]+"
        },
        {},
        {
            "indicator.*"
        },
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?awin1\\.com",
        true,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?awin1\\.com\\/cread\\.php?.*ued=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?zattini\\.com\\.br",
        false,
        {
            "campaign"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?spotify\\.com",
        false,
        {
            "splot"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?mozilla\\.org",
        false,
        {
            "redirect[a-z]+"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?cooldeal\\.by",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?cooldeal\\.by\\/redirect\\/.*to=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?bbc\\.com",
        false,
        {
            "ns_[a-z]+"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?vk\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?vk\\.com\\/away\\.php?.*to=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?medium\\.com",
        false,
        {
            "sectionName"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?play\\.app\\.goo\\.gl",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?play\\.app\\.goo\\.gl\\/?.*link=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?netshoes\\.com\\.br",
        false,
        {
            "af_.+",
            "clickid",
            "pid"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?hurb\\.com",
        false,
        {
            "cmp"
        },
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?hurb\\.com\\/aud\\/([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?submarino\\.com\\.br",
        false,
        {
            "chave"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?girafa\\.com\\.br",
        false,
        {
            "lmdsid"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?iqbroker\\.co",
        false,
        {},
        {},
        {
            "af[a-z_]+",
            "pid",
            "c"
        },
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?extra\\.com\\.br",
        false,
        {
            "IdSku"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?crunchyroll\\.com",
        false,
        {},
        {},
        {
            "from"
        },
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?deezer\\.com",
        false,
        {
            "redirect_[a-z]+"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?banggood\\.com",
        false,
        {},
        {},
        {
            "zf",
            "_branch_match_id"
        },
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?awsevents\\.com",
        false,
        {
            "trk[a-zA-Z]*",
            "sc_[a-z]+"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?ubi\\.com",
        false,
        {
            "cache"
        },
        {},
        {},
        {},
        {}
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?allshops\\.me",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?allshops\\.me\\/redirect\\/.+to=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?shareasale\\.com",
        false,
        {},
        {},
        {},
        {},
        {
            "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?shareasale\\.com\\/r\\.cfm.+urllink=([^&]*)"
        }
    ),
    Ruleset(
        "^https?:\\/\\/(?:[a-z0-9-]+\\.)*?udemy\\.com",
        false,
        {
            "ran[A-Za-z]+",
            "LSNPUBID"
        },
        {},
        {},
        {},
        {}
    )
};
