name: Java Ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up NDK r24-beta2
      uses: nttld/setup-ndk@main
      id: setup-ndk
      with:
        ndk-version: r24-beta2
    - name: Set up JDK 17
      uses: actions/setup-java@main
      with:
        java-version: 17
        distribution: temurin
    - name: Set up Nim devel
      uses: jiro4989/setup-nim-action@master
      with:
        nim-version: "devel"
    - name: Install helper tool
      working-directory: app/src/main/jni/tool
      run: nimble install --define:ssl --accept
    - name: Checkout PCRE source
      working-directory: app/src/main/jni/tool
      run: tool download pcre
    - name: Build PCRE
      working-directory: app/src/main/jni/tool
      env:
        ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: |
        tool build pcre --architecture:arm
        tool build pcre --architecture:arm64
        tool build pcre --architecture:i386
        tool build pcre --architecture:amd64
    - name: Checkout LibreSSL source
      working-directory: app/src/main/jni/tool
      run: tool download libressl
    - name: Apply LibreSSL patches
      working-directory: app/src/main/jni/tool
      run: tool patch libressl
    - name: Build LibreSSL
      working-directory: app/src/main/jni/tool
      env:
        ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: |
        tool build libressl --architecture:arm
        tool build libressl --architecture:arm64
        tool build libressl --architecture:i386
        tool build libressl --architecture:amd64
    - name: Build JNI wrapper
      working-directory: app/src/main/jni/tool
      env:
        ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: |
        tool build wrapper --architecture:arm
        tool build wrapper --architecture:arm64
        tool build wrapper --architecture:i386
        tool build wrapper --architecture:amd64
    - name: Assemble APK
      run: |
        ./gradlew --no-daemon assembleRelease
        
        mv app/build/outputs/apk/release/app-x86-release-unsigned.apk app/build/outputs/apk/release/app-x86-release.apk
        mv app/build/outputs/apk/release/app-x86_64-release-unsigned.apk app/build/outputs/apk/release/app-x86_64-release.apk
        mv app/build/outputs/apk/release/app-arm64-v8a-release-unsigned.apk app/build/outputs/apk/release/app-arm64-v8a-release.apk
        mv app/build/outputs/apk/release/app-armeabi-v7a-release-unsigned.apk app/build/outputs/apk/release/app-armeabi-v7a-release.apk
    - uses: r0adkll/sign-android-release@master
      name: Sign APK
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "30.0.2"
    - name: Upload APK
      uses: actions/upload-artifact@main
      with:
        name: build
        path: app/build/outputs/apk/release/app-*-release-signed.apk